import { useEffect, useState } from "react";
import { Copy, FileText, Languages, Loader2 } from "lucide-react";
import type { DocumentResult, FileSelection } from "@/types/api";
import { api } from "@/lib/bridge";
import { FilePicker } from "./FilePicker";
import { LanguageSelect } from "./LanguageSelect";
import { Empty, ErrorMessage, Loading } from "./ImageTranslator";

export function DocumentTranslator({ dropPath }: { dropPath?: string }) {
  const [file, setFile] = useState<FileSelection | null>(null); const [language, setLanguage] = useState("en"); const [result, setResult] = useState<DocumentResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const select = async (path?: string) => { try { const value = path ? await api.loadFile(path, "document") : await api.pickFile("document"); if (!value.path) return; setFile(value); setResult(null); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not read document"); } };
  useEffect(() => { if (dropPath) void select(dropPath); }, [dropPath]);
  const translate = async () => { if (!file || !language) return; setBusy(true); setError(""); try { setResult(await api.document({ path: file.path, language })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Document translation failed"); } finally { setBusy(false); } };
  const copy = async () => { if (!result) return; await navigator.clipboard.writeText(result.segments.map((segment) => segment.translation).join("\n\n")); };
  return <div className="desktop-workspace h-full min-h-[30rem] grid-cols-1 md:grid-cols-[.8fr_1.2fr]"><section className="desktop-pane p-4"><FilePicker kind="document" selection={file} onPick={() => void select()} onClear={() => { setFile(null); setResult(null); }} /><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Localize extracts text from PDF, EPUB, MOBI, DOCX, XLSX, and PPTX, then translates ordered sections. Office layout is not recreated.</p></section><section className="desktop-pane flex min-h-72 flex-col"><header className="flex h-11 items-center justify-between gap-2 border-b px-1"><LanguageSelect value={language} onChange={setLanguage} /><div className="flex items-center gap-1 pr-1"><button onClick={copy} disabled={!result} className="app-button app-button-secondary"><Copy className="size-4" /></button><button onClick={translate} disabled={!file || !language || busy} className="app-button app-button-primary">{busy ? <Loader2 className="size-4 animate-spin" /> : <Languages className="size-4" />}{busy ? "Translating" : "Translate"}</button></div></header><div className="min-h-52 flex-1 overflow-auto">{busy ? <Loading label="Extracting and translating document sections…" /> : error ? <ErrorMessage message={error} /> : result ? <DocumentOutput result={result} /> : <Empty text="Upload a supported document to view its original and translated text." />}</div></section></div>;
}

function DocumentOutput({ result }: { result: DocumentResult }) { return <div><div className="sticky top-0 grid grid-cols-2 border-b bg-card/95 text-[.65rem] font-semibold uppercase tracking-wide text-muted-foreground backdrop-blur"><div className="border-r px-4 py-2">Original</div><div className="px-4 py-2">Translation</div></div>{result.segments.map((segment) => <div key={segment.ordinal} className="grid grid-cols-2 border-b last:border-b-0"><div className="min-w-0 border-r p-4"><span className="mb-2 block font-mono text-xs text-muted-foreground">{segment.ordinal}</span><p className="whitespace-pre-wrap break-words text-sm leading-relaxed text-muted-foreground">{segment.original}</p></div><div className="min-w-0 p-4"><span className="mb-2 block font-mono text-xs text-muted-foreground">{segment.ordinal}</span><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{segment.translation}</p></div></div>)}</div>; }
