import { useMemo, useRef, useState } from "react";
import { Check, Copy, Languages, Loader2, Mic, Radio, Search, Square, X } from "lucide-react";
import { beginAudioCapture, toBase64, wavFromSamples, type AudioCapture } from "@/lib/audioCapture";
import { api } from "@/lib/bridge";
import { LanguageSelect } from "./LanguageSelect";
import { TranslationAlternatives } from "./TranslationAlternatives";
import { VoiceInputDialog } from "./VoiceInputDialog";

const maxChars = 5000;
const liveSilenceMS = 720;
const maxLivePhraseSamples = 16_000 * 12;
const minLivePhraseSamples = 16_000 / 3;
const minLiveSpeechSamples = 16_000 / 8;
const livePreRollSamples = 16_000 * 0.32;
const liveStartThreshold = 0.018;
const liveContinueThreshold = 0.01;
const liveStartFrames = 2;

export function TextTranslator({ initialInput = "" }: { initialInput?: string }) {
  const [input, setInput] = useState(initialInput); const [output, setOutput] = useState(""); const [translationSource, setTranslationSource] = useState(""); const [translationLanguage, setTranslationLanguage] = useState("en"); const [language, setLanguage] = useState("en"); const [detected, setDetected] = useState<string[]>([]); const [busy, setBusy] = useState<"translate" | "detect" | null>(null); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [voiceOpen, setVoiceOpen] = useState(false); const [microphoneId, setMicrophoneId] = useState<string | undefined>(); const [speechLanguage, setSpeechLanguage] = useState("auto"); const [live, setLive] = useState(false);
  const inputRef = useRef<HTMLTextAreaElement | null>(null); const liveCapture = useRef<AudioCapture | null>(null); const liveActive = useRef(false); const liveChunks = useRef<Int16Array[]>([]); const liveSamples = useRef(0); const livePreRoll = useRef<Int16Array[]>([]); const livePreRollCount = useRef(0); const liveHasSpeech = useRef(false); const liveSpeechSamples = useRef(0); const liveStartCount = useRef(0); const lastSpeech = useRef(0); const insertionAnchor = useRef(0); const insertedLength = useRef(0); const speechLanguageRef = useRef("auto"); const queue = useRef(Promise.resolve());

  const overLimit = input.length > maxChars; const canTranslate = Boolean(input.trim() && language && !overLimit && !busy && !live); const detectedLabel = useMemo(() => detected.map((code) => code.toUpperCase()).join(", "), [detected]);
  const insertAtCaret = (text: string) => { const element = inputRef.current; const start = element?.selectionStart ?? input.length; setInput((current) => insertText(current, start, text)); window.setTimeout(() => { if (element) { const caret = start + insertedTextLength(input, start, text); element.focus(); element.setSelectionRange(caret, caret); } }, 0); };
  const translate = async () => { if (!canTranslate) return; const source = input; const targetLanguage = language; setBusy("translate"); setError(""); try { const translation = await api.translate(source, targetLanguage); setOutput(translation); setTranslationSource(source); setTranslationLanguage(targetLanguage); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not translate text"); } finally { setBusy(null); } };
  const detect = async () => { if (!input.trim()) return; setBusy("detect"); setError(""); try { setDetected(await api.detect(input)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not detect language"); } finally { setBusy(null); } };
  const copy = async () => { if (!output) return; await navigator.clipboard.writeText(output); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  const clear = () => { if (live) return; setInput(""); setOutput(""); setTranslationSource(""); setDetected([]); setError(""); };
  const loadSpeechSettings = async () => { const [settings, status] = await Promise.all([api.getSettings(), api.whisperStatus()]); if (!status.available) throw new Error(status.message); const config = { microphoneId: settings.whisperCpp.microphoneId, language: settings.whisperCpp.language || "auto" }; setMicrophoneId(config.microphoneId); setSpeechLanguage(config.language); speechLanguageRef.current = config.language; return config; };
  const openVoice = async () => { setError(""); try { await loadSpeechSettings(); setVoiceOpen(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Configure Whisper.cpp in Settings before recording"); } };
  const resetLivePhrase = () => { liveChunks.current = []; liveSamples.current = 0; livePreRoll.current = []; livePreRollCount.current = 0; liveHasSpeech.current = false; liveSpeechSamples.current = 0; liveStartCount.current = 0; lastSpeech.current = 0; };
  const rememberLivePreRoll = (samples: Int16Array) => { livePreRoll.current.push(samples); livePreRollCount.current += samples.length; while (livePreRollCount.current > livePreRollSamples && livePreRoll.current.length > 1) { const removed = livePreRoll.current.shift(); livePreRollCount.current -= removed?.length ?? 0; } };
  const flushLive = (force = false) => {
    if (!liveActive.current || !liveHasSpeech.current || liveSamples.current < minLivePhraseSamples || liveSpeechSamples.current < minLiveSpeechSamples) return;
    if (!force && Date.now() - lastSpeech.current < liveSilenceMS && liveSamples.current < maxLivePhraseSamples) return;
    const wav = wavFromSamples(liveChunks.current); resetLivePhrase(); if (!wav) return;
    queue.current = queue.current.then(async () => { const result = await api.transcribeCapturedAudio({ wavBase64: toBase64(wav), language: speechLanguageRef.current }); if (!liveActive.current || !result.text.trim()) return; const text = result.text.trim(); setInput((current) => { const position = insertionAnchor.current + insertedLength.current; const inserted = insertionText(current, position, text); insertedLength.current += inserted.length; return current.slice(0, position) + inserted + current.slice(position); }); }).catch((reason) => { if (liveActive.current) setError(reason instanceof Error ? reason.message : "Live transcription failed"); });
  };
  const receiveLiveChunk = (chunk: { samples: Int16Array; rms: number }) => {
    if (!liveActive.current) return;
    if (!liveHasSpeech.current) {
      rememberLivePreRoll(chunk.samples);
      liveStartCount.current = chunk.rms >= liveStartThreshold ? liveStartCount.current + 1 : 0;
      if (liveStartCount.current < liveStartFrames) return;
      liveHasSpeech.current = true; liveChunks.current = livePreRoll.current; liveSamples.current = livePreRollCount.current; livePreRoll.current = []; livePreRollCount.current = 0; liveSpeechSamples.current = chunk.samples.length * liveStartFrames; lastSpeech.current = Date.now();
      return;
    }
    liveChunks.current.push(chunk.samples); liveSamples.current += chunk.samples.length;
    if (chunk.rms >= liveContinueThreshold) { liveSpeechSamples.current += chunk.samples.length; lastSpeech.current = Date.now(); }
    flushLive();
  };
  const startLive = async () => { if (live) return; setError(""); try { const config = await loadSpeechSettings(); const element = inputRef.current; insertionAnchor.current = element?.selectionStart ?? input.length; insertedLength.current = 0; resetLivePhrase(); liveActive.current = true; const active = await beginAudioCapture(config.microphoneId, receiveLiveChunk); liveCapture.current = active; setLive(true); } catch (reason) { liveActive.current = false; resetLivePhrase(); setError(reason instanceof Error ? reason.message : "Could not start live transcription"); } };
  const stopLive = async () => { if (!live) return; const active = liveCapture.current; liveCapture.current = null; await active?.stop(); flushLive(true); await queue.current; liveActive.current = false; resetLivePhrase(); setLive(false); inputRef.current?.focus(); };

  return <><div className="translator-frame grid h-full min-h-[30rem] grid-cols-1 gap-4 md:grid-cols-2 md:gap-0 md:overflow-hidden md:rounded-[.65rem] md:border md:bg-card md:shadow-sm">
    <section className="surface translator-pane translator-input flex min-h-72 flex-col"><header className="flex h-11 items-center justify-between border-b px-2"><div className="flex min-w-0 items-center gap-1"><button onClick={() => void openVoice()} disabled={live || busy !== null} className="app-button app-button-outline" aria-label="Open voice input"><Mic className="size-4" /><span className="hidden lg:inline">Voice</span></button><button onClick={() => void (live ? stopLive() : startLive())} disabled={busy !== null} className={live ? "app-button app-button-danger" : "app-button app-button-outline"} aria-label={live ? "Stop live transcription" : "Start live transcription"}>{live ? <Square className="size-3.5 fill-current" /> : <Radio className="size-4" />}<span className="hidden lg:inline">{live ? "Stop" : "Live"}</span></button></div><div className="flex min-w-0 items-center">{detectedLabel ? <span className="flex items-center gap-2 text-sm text-muted-foreground">Detected <b className="rounded bg-muted px-1.5 py-0.5 font-mono text-xs text-foreground">{detectedLabel}</b><button onClick={() => setDetected([])} className="app-button !min-h-0 !p-1" aria-label="Clear detected language"><X className="size-3.5" /></button></span> : <button onClick={detect} disabled={!input.trim() || busy !== null || live} className="app-button"><Search className="size-4" />{busy === "detect" ? "Detecting…" : "Detect language"}</button>}</div></header><textarea ref={inputRef} value={input} readOnly={live} onChange={(event) => setInput(event.target.value)} placeholder={live ? "Listening and inserting speech…" : "Enter text to translate…"} spellCheck={false} className="min-h-52 flex-1 resize-none bg-transparent px-4 py-3.5 text-[.95rem] leading-relaxed outline-none read-only:cursor-not-allowed" /><footer className="flex h-11 items-center justify-between border-t px-3"><span className={overLimit ? "font-mono text-xs text-destructive" : "font-mono text-xs text-muted-foreground"}>{input.length.toLocaleString()} / {maxChars.toLocaleString()}</span><button onClick={clear} disabled={!input || live} className="app-button">Clear</button></footer></section>
    <section className="surface translator-pane flex min-h-72 flex-col"><header className="flex h-11 items-center justify-between gap-2 border-b px-1"><LanguageSelect value={language} onChange={setLanguage} /><div className="flex shrink-0 items-center pr-1"><button onClick={translate} disabled={!canTranslate} className="app-button app-button-primary">{busy === "translate" ? <Loader2 className="size-4 animate-spin" /> : <Languages className="size-4" />}{busy === "translate" ? "Translating" : "Translate"}</button></div></header><div className="min-h-52 flex-1 overflow-auto px-4 py-3.5 whitespace-pre-wrap break-words text-[.95rem] leading-relaxed">{busy === "translate" ? <div className="space-y-3 pt-2"><div className="h-4 w-11/12 animate-pulse rounded bg-muted" /><div className="h-4 w-8/12 animate-pulse rounded bg-muted" /><div className="h-4 w-10/12 animate-pulse rounded bg-muted" /></div> : error ? <div className="text-destructive"><b>Translation failed</b><p className="mt-1 text-sm text-muted-foreground">{error}</p></div> : output ? <TranslationAlternatives text={output} sourceText={translationSource} language={translationLanguage} onReplace={(range, replacement) => setOutput((current) => `${current.slice(0, range.start)}${replacement}${current.slice(range.end)}`)} /> : <span className="text-muted-foreground">Your translation will appear here.</span>}</div><footer className="flex h-11 items-center justify-between border-t px-3"><span className="font-mono text-xs text-muted-foreground">{output.length.toLocaleString()} chars</span><button onClick={copy} disabled={!output} className="app-button app-button-secondary">{copied ? <Check className="size-4" /> : <Copy className="size-4" />}{copied ? "Copied" : "Copy"}</button></footer></section>
  </div>{voiceOpen && <VoiceInputDialog microphoneId={microphoneId} language={speechLanguage} onClose={() => setVoiceOpen(false)} onInsert={insertAtCaret} />}</>;
}

function insertionText(current: string, position: number, text: string) { const prefix = position > 0 && !/\s$/.test(current.slice(0, position)) && !/^[,.;:!?)]/.test(text) ? " " : ""; const suffix = position < current.length && !/^\s/.test(current.slice(position)) && !/[\s(]$/.test(text) ? " " : ""; return `${prefix}${text}${suffix}`; }
function insertText(current: string, position: number, text: string) { return `${current.slice(0, position)}${insertionText(current, position, text)}${current.slice(position)}`; }
function insertedTextLength(current: string, position: number, text: string) { return insertionText(current, position, text).length; }
