// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {options} from '../models';

export function DeleteLocalLlamaModel(arg1:string):Promise<void>;

export function DeleteOllamaModel(arg1:string):Promise<void>;

export function DeleteWhisperModel(arg1:string):Promise<void>;

export function DetectLanguage(arg1:string):Promise<Array<string>>;

export function ExtractImageText(arg1:string):Promise<string>;

export function GetApplicationVersion():Promise<string>;

export function GetDefaultPrompts():Promise<domain.PromptSettings>;

export function GetHuggingFaceFiles(arg1:string):Promise<Array<domain.HuggingFaceFile>>;

export function GetLlamaCppRuntimeStatus():Promise<domain.LlamaCppRuntimeStatus>;

export function GetMuPDFRuntimeStatus():Promise<domain.MuPDFRuntimeStatus>;

export function GetProviderStatus():Promise<domain.ProviderStatus>;

export function GetSettings():Promise<domain.Settings>;

export function GetTranslationVariants(arg1:domain.TranslationVariantsRequest):Promise<domain.TranslationVariantsResult>;

export function GetUpdateAvailability():Promise<domain.UpdateAvailability>;

export function GetWhisperCppRuntimeStatus():Promise<domain.WhisperCppRuntimeStatus>;

export function GetWhisperStatus():Promise<domain.WhisperStatus>;

export function InstallHuggingFaceModel(arg1:domain.HuggingFaceInstallRequest):Promise<domain.ModelInfo>;

export function InstallLlamaCppRuntime(arg1:domain.LlamaCppRuntimeInstallRequest):Promise<void>;

export function InstallMuPDFRuntime(arg1:domain.MuPDFRuntimeInstallRequest):Promise<void>;

export function InstallWhisperCppRuntime(arg1:domain.WhisperCppRuntimeInstallRequest):Promise<void>;

export function InstallWhisperModel(arg1:domain.WhisperModelInstallRequest):Promise<domain.WhisperModel>;

export function ListActiveProviderModels():Promise<Array<domain.ModelInfo>>;

export function ListLlamaCppReleases():Promise<Array<domain.LlamaCppRelease>>;

export function ListLocalLlamaModels():Promise<Array<domain.ModelInfo>>;

export function ListMuPDFReleases():Promise<Array<domain.MuPDFRelease>>;

export function ListOllamaModels():Promise<Array<domain.ModelInfo>>;

export function ListWhisperCppReleases():Promise<Array<domain.WhisperCppRelease>>;

export function ListWhisperModels():Promise<Array<domain.WhisperModel>>;

export function LoadFile(arg1:string,arg2:string):Promise<domain.FileSelection>;

export function LoadLocalizationFile(arg1:domain.LocalizationFileRequest):Promise<domain.LocalizationFile>;

export function OpenLatestRelease():Promise<void>;

export function OpenOllamaCatalog():Promise<void>;

export function PickFile(arg1:string):Promise<domain.FileSelection>;

export function PickLlamaModelDirectory():Promise<string>;

export function PickLocalizationFile(arg1:domain.LocalizationFormat):Promise<domain.FileSelection>;

export function PickWhisperModelDirectory():Promise<string>;

export function PullOllamaModel(arg1:string):Promise<void>;

export function SaveLocalizationFile(arg1:domain.LocalizationSaveRequest):Promise<domain.LocalizationSaveResult>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;

export function SearchHuggingFaceModels(arg1:string):Promise<Array<domain.HuggingFaceModel>>;

export function SecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function TranscribeAudio(arg1:domain.AudioTranscriptionRequest):Promise<domain.AudioTranscriptionResult>;

export function TranscribeCapturedAudio(arg1:domain.CapturedAudioTranscriptionRequest):Promise<domain.AudioTranscriptionResult>;

export function TranslateDocument(arg1:domain.DocumentRequest):Promise<domain.DocumentResult>;

export function TranslateImage(arg1:domain.ImageRequest):Promise<domain.ImageResult>;

export function TranslateLocalizationEntries(arg1:domain.LocalizationTranslationRequest):Promise<domain.LocalizationTranslationResult>;

export function TranslateText(arg1:domain.TranslateRequest):Promise<string>;
