// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLocalLlamaModel(arg1) {
  return window['go']['app']['Desktop']['DeleteLocalLlamaModel'](arg1);
}

export function DeleteOllamaModel(arg1) {
  return window['go']['app']['Desktop']['DeleteOllamaModel'](arg1);
}

export function DeleteWhisperModel(arg1) {
  return window['go']['app']['Desktop']['DeleteWhisperModel'](arg1);
}

export function DetectLanguage(arg1) {
  return window['go']['app']['Desktop']['DetectLanguage'](arg1);
}

export function ExtractImageText(arg1) {
  return window['go']['app']['Desktop']['ExtractImageText'](arg1);
}

export function GetApplicationVersion() {
  return window['go']['app']['Desktop']['GetApplicationVersion']();
}

export function GetDefaultPrompts() {
  return window['go']['app']['Desktop']['GetDefaultPrompts']();
}

export function GetHuggingFaceFiles(arg1) {
  return window['go']['app']['Desktop']['GetHuggingFaceFiles'](arg1);
}

export function GetLlamaCppRuntimeStatus() {
  return window['go']['app']['Desktop']['GetLlamaCppRuntimeStatus']();
}

export function GetMuPDFRuntimeStatus() {
  return window['go']['app']['Desktop']['GetMuPDFRuntimeStatus']();
}

export function GetProviderStatus() {
  return window['go']['app']['Desktop']['GetProviderStatus']();
}

export function GetSettings() {
  return window['go']['app']['Desktop']['GetSettings']();
}

export function GetTranslationVariants(arg1) {
  return window['go']['app']['Desktop']['GetTranslationVariants'](arg1);
}

export function GetUpdateAvailability() {
  return window['go']['app']['Desktop']['GetUpdateAvailability']();
}

export function GetWhisperCppRuntimeStatus() {
  return window['go']['app']['Desktop']['GetWhisperCppRuntimeStatus']();
}

export function GetWhisperStatus() {
  return window['go']['app']['Desktop']['GetWhisperStatus']();
}

export function InstallHuggingFaceModel(arg1) {
  return window['go']['app']['Desktop']['InstallHuggingFaceModel'](arg1);
}

export function InstallLlamaCppRuntime(arg1) {
  return window['go']['app']['Desktop']['InstallLlamaCppRuntime'](arg1);
}

export function InstallMuPDFRuntime(arg1) {
  return window['go']['app']['Desktop']['InstallMuPDFRuntime'](arg1);
}

export function InstallWhisperCppRuntime(arg1) {
  return window['go']['app']['Desktop']['InstallWhisperCppRuntime'](arg1);
}

export function InstallWhisperModel(arg1) {
  return window['go']['app']['Desktop']['InstallWhisperModel'](arg1);
}

export function ListActiveProviderModels() {
  return window['go']['app']['Desktop']['ListActiveProviderModels']();
}

export function ListLlamaCppReleases() {
  return window['go']['app']['Desktop']['ListLlamaCppReleases']();
}

export function ListLocalLlamaModels() {
  return window['go']['app']['Desktop']['ListLocalLlamaModels']();
}

export function ListMuPDFReleases() {
  return window['go']['app']['Desktop']['ListMuPDFReleases']();
}

export function ListOllamaModels() {
  return window['go']['app']['Desktop']['ListOllamaModels']();
}

export function ListWhisperCppReleases() {
  return window['go']['app']['Desktop']['ListWhisperCppReleases']();
}

export function ListWhisperModels() {
  return window['go']['app']['Desktop']['ListWhisperModels']();
}

export function LoadFile(arg1, arg2) {
  return window['go']['app']['Desktop']['LoadFile'](arg1, arg2);
}

export function LoadLocalizationFile(arg1) {
  return window['go']['app']['Desktop']['LoadLocalizationFile'](arg1);
}

export function OpenLatestRelease() {
  return window['go']['app']['Desktop']['OpenLatestRelease']();
}

export function OpenOllamaCatalog() {
  return window['go']['app']['Desktop']['OpenOllamaCatalog']();
}

export function PickFile(arg1) {
  return window['go']['app']['Desktop']['PickFile'](arg1);
}

export function PickLlamaModelDirectory() {
  return window['go']['app']['Desktop']['PickLlamaModelDirectory']();
}

export function PickLocalizationFile(arg1) {
  return window['go']['app']['Desktop']['PickLocalizationFile'](arg1);
}

export function PickWhisperModelDirectory() {
  return window['go']['app']['Desktop']['PickWhisperModelDirectory']();
}

export function PullOllamaModel(arg1) {
  return window['go']['app']['Desktop']['PullOllamaModel'](arg1);
}

export function SaveLocalizationFile(arg1) {
  return window['go']['app']['Desktop']['SaveLocalizationFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['Desktop']['SaveSettings'](arg1);
}

export function SearchHuggingFaceModels(arg1) {
  return window['go']['app']['Desktop']['SearchHuggingFaceModels'](arg1);
}

export function SecondInstance(arg1) {
  return window['go']['app']['Desktop']['SecondInstance'](arg1);
}

export function TranscribeAudio(arg1) {
  return window['go']['app']['Desktop']['TranscribeAudio'](arg1);
}

export function TranscribeCapturedAudio(arg1) {
  return window['go']['app']['Desktop']['TranscribeCapturedAudio'](arg1);
}

export function TranslateDocument(arg1) {
  return window['go']['app']['Desktop']['TranslateDocument'](arg1);
}

export function TranslateImage(arg1) {
  return window['go']['app']['Desktop']['TranslateImage'](arg1);
}

export function TranslateLocalizationEntries(arg1) {
  return window['go']['app']['Desktop']['TranslateLocalizationEntries'](arg1);
}

export function TranslateText(arg1) {
  return window['go']['app']['Desktop']['TranslateText'](arg1);
}
