import * as Desktop from "../../wailsjs/go/app/Desktop";
import type { DocumentRequest, HuggingFaceFile, HuggingFaceInstallRequest, HuggingFaceModel, ImageResult, ModelInfo, ProviderStatus, Settings, FileSelection, DocumentResult, PromptSettings, TranslationVariantsRequest, TranslationVariantsResult, LlamaCppRelease, LlamaCppRuntimeInstallRequest, LlamaCppRuntimeStatus, MuPDFRelease, MuPDFRuntimeInstallRequest, MuPDFRuntimeStatus, WhisperCppRelease, WhisperCppRuntimeInstallRequest, WhisperCppRuntimeStatus, WhisperModel, WhisperModelInstallRequest, WhisperStatus, AudioTranscriptionRequest, CapturedAudioTranscriptionRequest, AudioTranscriptionResult, UpdateAvailability, LocalizationFormat, LocalizationFileRequest, LocalizationFile, LocalizationTranslationRequest, LocalizationTranslationResult, LocalizationSaveRequest, LocalizationSaveResult } from "./contracts";

// The generated bindings own the transport. These narrow casts keep React tied
// to stable feature contracts instead of Wails generator class implementations.
export const api = {
  getSettings: () => Desktop.GetSettings() as unknown as Promise<Settings>,
  applicationVersion: () => Desktop.GetApplicationVersion(),
  defaultPrompts: () => Desktop.GetDefaultPrompts() as unknown as Promise<PromptSettings>,
  saveSettings: (value: Settings) => Desktop.SaveSettings(value as never),
  providerStatus: () => Desktop.GetProviderStatus() as unknown as Promise<ProviderStatus>,
  updateAvailability: () => Desktop.GetUpdateAvailability() as unknown as Promise<UpdateAvailability>,
  openLatestRelease: () => Desktop.OpenLatestRelease(),
  activeModels: () => Desktop.ListActiveProviderModels() as unknown as Promise<ModelInfo[]>,
  ollamaModels: () => Desktop.ListOllamaModels() as unknown as Promise<ModelInfo[]>,
  pullOllama: (model: string) => Desktop.PullOllamaModel(model),
  deleteOllamaModel: (id: string) => Desktop.DeleteOllamaModel(id),
  openOllamaCatalog: () => Desktop.OpenOllamaCatalog(),
  searchHF: (query: string) => Desktop.SearchHuggingFaceModels(query) as unknown as Promise<HuggingFaceModel[]>,
  hfFiles: (repository: string) => Desktop.GetHuggingFaceFiles(repository) as unknown as Promise<HuggingFaceFile[]>,
  installHF: (request: HuggingFaceInstallRequest) => Desktop.InstallHuggingFaceModel(request as never) as unknown as Promise<ModelInfo>,
  localModels: () => Desktop.ListLocalLlamaModels() as unknown as Promise<ModelInfo[]>,
  deleteLocalModel: (id: string) => Desktop.DeleteLocalLlamaModel(id),
  pickLlamaModelDirectory: () => Desktop.PickLlamaModelDirectory(),
  llamaReleases: () => Desktop.ListLlamaCppReleases() as unknown as Promise<LlamaCppRelease[]>,
  llamaRuntimeStatus: () => Desktop.GetLlamaCppRuntimeStatus() as unknown as Promise<LlamaCppRuntimeStatus>,
  installLlamaRuntime: (request: LlamaCppRuntimeInstallRequest) => Desktop.InstallLlamaCppRuntime(request as never),
  mupdfReleases: () => Desktop.ListMuPDFReleases() as unknown as Promise<MuPDFRelease[]>,
  mupdfRuntimeStatus: () => Desktop.GetMuPDFRuntimeStatus() as unknown as Promise<MuPDFRuntimeStatus>,
  installMuPDFRuntime: (request: MuPDFRuntimeInstallRequest) => Desktop.InstallMuPDFRuntime(request as never),
  whisperReleases: () => Desktop.ListWhisperCppReleases() as unknown as Promise<WhisperCppRelease[]>,
  whisperRuntimeStatus: () => Desktop.GetWhisperCppRuntimeStatus() as unknown as Promise<WhisperCppRuntimeStatus>,
  installWhisperRuntime: (request: WhisperCppRuntimeInstallRequest) => Desktop.InstallWhisperCppRuntime(request as never),
  whisperStatus: () => Desktop.GetWhisperStatus() as unknown as Promise<WhisperStatus>,
  whisperModels: () => Desktop.ListWhisperModels() as unknown as Promise<WhisperModel[]>,
  installWhisperModel: (request: WhisperModelInstallRequest) => Desktop.InstallWhisperModel(request as never) as unknown as Promise<WhisperModel>,
  deleteWhisperModel: (id: string) => Desktop.DeleteWhisperModel(id),
  pickWhisperModelDirectory: () => Desktop.PickWhisperModelDirectory(),
  pickFile: (kind: "image" | "document" | "audio") => Desktop.PickFile(kind) as unknown as Promise<FileSelection>,
  loadFile: (path: string, kind: "image" | "document" | "audio") => Desktop.LoadFile(path, kind) as unknown as Promise<FileSelection>,
  translate: (text: string, language: string) => Desktop.TranslateText({ text, language } as never),
  variants: (request: TranslationVariantsRequest) => Desktop.GetTranslationVariants(request as never) as unknown as Promise<TranslationVariantsResult>,
  detect: (text: string) => Desktop.DetectLanguage(text),
  transcribeAudio: (request: AudioTranscriptionRequest) => Desktop.TranscribeAudio(request as never) as unknown as Promise<AudioTranscriptionResult>,
  transcribeCapturedAudio: (request: CapturedAudioTranscriptionRequest) => Desktop.TranscribeCapturedAudio(request as never) as unknown as Promise<AudioTranscriptionResult>,
  ocr: (path: string) => Desktop.ExtractImageText(path),
  image: (path: string, language: string) => Desktop.TranslateImage({ path, language } as never) as unknown as Promise<ImageResult>,
  document: (request: DocumentRequest) => Desktop.TranslateDocument(request as never) as unknown as Promise<DocumentResult>,
  pickLocalizationFile: (format: LocalizationFormat) => Desktop.PickLocalizationFile(format) as unknown as Promise<FileSelection>,
  loadLocalizationFile: (request: LocalizationFileRequest) => Desktop.LoadLocalizationFile(request as never) as unknown as Promise<LocalizationFile>,
  translateLocalizationEntries: (request: LocalizationTranslationRequest) => Desktop.TranslateLocalizationEntries(request as never) as unknown as Promise<LocalizationTranslationResult>,
  saveLocalizationFile: (request: LocalizationSaveRequest) => Desktop.SaveLocalizationFile(request as never) as unknown as Promise<LocalizationSaveResult>,
};
